### ISSUE TITLE
Working with Processing 3?

### ISSUE THREAD

**Issue by yishiyang** [vialab/SMT#226]
Hi there,

I'm trying to use SMT with Processing 3 but keep getting problems running examples.

The error message says:
"ClassCastException: processing.core.PApplet$6 cannot be cast to javax.swing.JFrame"

Does SMT only work with Processing 2?
Please help!

Yishi

**Comment by mshancock** [comment]
Yes, unfortunately we don't currently have the resources to update this to Processing 3, though we would welcome any help in doing so!
